---
- name: Create Pool for App on F5
  when: dms_env in f5_pool_env_check and f5_pool_name not in (bigip_facts.ansible_net_ltm_pools | map(attribute='name') | list)
  delegate_to: localhost
  vars:
    f5_pool_env_check: "{{ f5_vs_data_pools[current_pool].sites | default('') }}"
    f5_pool_node_label: "{{ f5_vs_data_pools[current_pool].node_label | default('') }}"
    f5_pool_port_label: "{{ f5_vs_data_pools[current_pool].port_label | default('') }}"
    f5_pool_name: "{{ f5_vs_data_pools[current_pool]['legacy_name'][dms_env] | default(f5_vs_data_pools[current_pool].name+f5_pool_node_label+'_'+f5_pool_port_label+'_pool') }}"
    f5_pool_monitor: "{{ f5_vs_data_pools[current_pool].monitor | default('http') }}"
    f5_pool_description: "{{ f5_vs_data_pools[current_pool].desc | default('Pool for '+f5_vs_sitename) }}"
    f5_pool_lb_method: "{{ f5_vs_data_pools[current_pool].lb_method | default('least-connections-member') }}"
  bigip_pool:
    provider: "{{ f5_local_provider }}"
    state: present
    partition: Common
    name: "{{ f5_pool_name }}"
    monitors: "{{ f5_pool_monitor }}"
    description: "{{ f5_pool_description }}"
    lb_method: "{{ f5_pool_lb_method }}"
  loop: "{{ f5_vs_data_pools | list }}"
  loop_control:
    loop_var: current_pool
  tags:
    - f5_create_vs
    - f5_create_pool

