- hosts: f5_config 
  gather_facts: false
  connection: local
    
  tasks:

    - name: Update F5 VS pool member
      bigip_virtual_server:
        name: bmwpass.arkona.com_443_vs
        irules: "bmwpass.arkona.com_443_irule"        
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ user }}"
          password: "{{ password }}"
          validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      register: bigip_output
    
    - name: bigip_output OUTPUT
      debug:
        msg: "{{ bigip_output | to_nice_json}}"
