---
- name: Set F5 Pool Name Member is Being Added to
  debug:
    msg:
     - "{{f5_pool_env_check }}"
     - "{{f5_pool_node_label }}"
     - "{{f5_pool_port_label }}"
     - "{{f5_pool_name }}"
     - "{{f5_pool_service_port }}"
  tags:
    - f5_create_vs
    - f5_create_pool
    - f5_add_pool_members

- name: DEBUG Set F5 Pool Name Member is Being Added to
  debug:
    msg:
      - "{{ f5_pool_name }}"
      - "{{ hostvars[item.0].vm_name }}"
      - "{{ item.1 }}"
  loop: "{{ groups[f5_pool_inv_group] | product(f5_pool_service_port) | list}}"
  tags:
    - f5_create_vs
    - f5_create_pool
    - f5_add_pool_members

- name: Add App Node Members to "{{ f5_pool_name }}" on F5
  when: member_name + ':' + (service_port | string) not in (bigip_facts.ansible_net_ltm_pools | string)
  delegate_to: localhost
  vars:
    member_name: "{{ hostvars[item.0].vm_name }}"
    member_ip: "{{ hostvars[item.0].vm_ipaddress }}"
    service_port: "{{ item.1 }}"
  bigip_pool_member:
    provider: "{{ f5_local_provider }}"
    state: present
    pool: "{{ f5_pool_name }}"
    name: "{{ member_name }}"
    host: "{{ member_ip }}"
    port: "{{ service_port }}"
  loop: "{{ groups[f5_pool_inv_group] | product(f5_pool_service_port) | list}}"
  tags:
    - f5_create_vs
    - f5_create_pool
    - f5_add_pool_members

